# Generated by Django 4.2.9 on 2024-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True)),
                ('post_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
