# Generated by Django 4.2.9 on 2024-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0004_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
