# Generated by Django 4.2.9 on 2024-01-31 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0005_usercredential_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
