# Generated by Django 4.2.9 on 2024-01-31 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0006_usercredential_date_of_birth_usercredential_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_posts/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='user_posts/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='user_posts/video/')),
                ('date_of_Post', models.DateField(default=datetime.date(1900, 1, 1))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCredential.usercredential')),
            ],
        ),
    ]
