# Generated by Django 4.2.9 on 2024-02-01 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0008_friendship_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='userCredential.userpost')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCredential.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userpost',
            name='comments',
            field=models.ManyToManyField(related_name='commented_posts', through='userCredential.Comment', to='userCredential.userprofile'),
        ),
    ]
