# Generated by Django 4.2.9 on 2024-02-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0009_comment_userpost_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(choices=[('A', 'accept'), ('P', 'pending'), ('R', 'reject')]),
        ),
    ]
