# Generated by Django 4.2.9 on 2024-02-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0010_alter_friendrequest_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(choices=[('A', 'accept'), ('P', 'pending'), ('R', 'reject')], max_length=1),
        ),
    ]
