# Generated by Django 4.2.9 on 2024-02-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0012_alter_friendrequest_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userCredential.usercredential'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCredential.userpost'),
        ),
    ]
