# Generated by Django 4.2.9 on 2024-02-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0013_remove_comment_user_profile_remove_userpost_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='user2',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user1',
            new_name='user',
        ),
    ]
