# Generated by Django 4.2.9 on 2024-02-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0014_rename_user2_friendship_follower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCredential.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCredential.usercredential')),
            ],
        ),
    ]
