# Generated by Django 4.2.9 on 2024-02-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0015_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='post',
            new_name='user_post',
        ),
    ]
