# Generated by Django 4.2.9 on 2024-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0016_rename_post_report_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='video',
        ),
        migrations.AddField(
            model_name='userpost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
