# Generated by Django 4.2.9 on 2024-02-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0017_remove_userpost_audio_remove_userpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
