# Generated by Django 4.2.9 on 2024-02-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0022_alter_comment_user_alter_report_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
    ]
