# Generated by Django 4.2.9 on 2024-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0023_rename_followers_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
