# Generated by Django 4.2.9 on 2024-03-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0025_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='date_of_Post',
            new_name='date_of_post',
        ),
    ]
