# Generated by Django 4.2.9 on 2024-03-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCredential', '0027_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.CharField(default='', max_length=30),
        ),
    ]
